#!/bin/sh
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
java -classpath /usr/local/class/cs143/cool/lib/java-cup-11a.jar:/usr/local/class/cs143/cool/lib/jlex.jar:/usr/java/lib/rt.jar:$DIR Lexer $*
